### ISSUE TITLE
Error with 'import' and 'export'

### ISSUE THREAD

**Issue by marcofugaro** [tunnckoCore/rollup-plugin-prepack#11]
This is the error I get:

`'import' and 'export' may appear only with 'sourceType: module' (1:0)
SyntaxError`

I am trying to use this plugin in my repo [promisify-dom-selector](https://github.com/marcofugaro/promisify-dom-selector), I am guessing the error comes with it not  liking the keywords import and export, which I [don't transpile](https://github.com/marcofugaro/promisify-dom-selector/blob/master/.babelrc#L8) because of rollup.

Is this what it's happening?

**Comment by tunnckoCore** [comment]
Hm, interesting. Sorry about that.

I don't see that your repo is using this plugin? I'll try to clone your repo and install, and we'll see.

**Comment by tunnckoCore** [comment]
Yea, strangely fails. I found this issue https://github.com/facebook/prepack/issues/823, so please follow it and make some changes. This one too https://github.com/facebook/prepack/issues/454.

Probably one thing that you can try is to install exact `0.2.0` version of `prepack` in your project, so this plugin will use it instead.

**Comment by tunnckoCore** [comment]
Okey, seems related to #9, so i'll make that change and bump in major.

> Created bundle promisifyDOMSelector.min.js: 765 B → 383 B (gzip)

:package: with working `prepack` :)

_edit: it does not get much smaller, because there is not much to evaluate in that bundle, so it may not make sense to use `prepack` et al. :) Just saying it :)_

**Comment by marcofugaro** [comment]
Hey thanks for the help!

Yes I was just trying that out, I know it's useless with very small libraries :)

**Comment by tunnckoCore** [comment]
Thanks to you too, because that made me consider the #9 is correct issue. :)
