### ISSUE TITLE
No sourcemap generated

### ISSUE THREAD

**Issue by matheusml** [tunnckoCore/rollup-plugin-prepack#2]
I'm getting this warning using this plugin:

```
Sourcemap is likely to be incorrect: a plugin ('prepack') was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
https://github.com/rollup/rollup/wiki/Troubleshooting#sourcemap-is-likely-to-be-incorrect
```

After reading the rollup wiki, it seems that this plugin is not generating a sourcemap after the prepack transformation:

> Usually, a plugin will only omit the sourcemap if it (the plugin, not the bundle) was configured with sourceMap: false – so all you need to do is change that. If the plugin doesn't generate a sourcemap, consider raising an issue with the plugin author.

**Comment by tunnckoCore** [comment]
Did you pass options to the plugin? You should pass sourceMaps option to it, so prepack will generate and return it.

Consult https://prepack.io/getting-started.html: pass  `sourceMaps`. This plugin does almost nothing , it just wraps it and returns what it returns.
